FROM php:7.4-apache

RUN apt-get update -y && apt-get install -y libmcrypt-dev libzip-dev libonig-dev zip uzip

WORKDIR /app
COPY . /app

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN docker-php-ext-install pdo mbstring

RUN composer install --no-scripts --no-autoloader

RUN composer dump-autoload

EXPOSE 8000

CMD php artisan server --host=0.0.0.0 --port=8000
